title: "The Price of Fairness in Algorithmic Decision-Making"
description: "A comparative machine learning study on the trade-off between predictive performance and algorithmic fairness using the Adult Census Income dataset."

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - literature.md
  - methodology.md
  - results.md
  - fairness.md
  - tradeoff.md
  - kfold.md
  - conclusion.md

show_excerpts: false

minima:
  skin: classic

# SEO polish
author: "Alperen ALAÇERİ"
email: "250708029@samsun.edu.tr"

# GitHub Pages friendly
github:
  is_project_page: true